Oracle Docs
VenusProtocol/venus-protocol-documentation pull request #23
Opened 2022-11-23 13:03 UTC by web3rover

2022-11-24 13:21 UTC, 0xlucian requested changes

2022-11-24 13:21 UTC, 0xlucian commented on oracle/ResillientOracle.md
> +Keeping this in mind, we have designed a resilient oracle which uses multiple oracle sources to validate prices and fallback mechanisms to provide accurate prices and protect from oracle attacks. Cur
can we put those line like an introduction before line 5? Isn't this more like an introduction to oracles rather than details?

2022-11-24 13:21 UTC, 0xlucian commented on oracle/ResillientOracle.md
> +The way the resilient oracle works is for every market (vToken) we configure the main, pivot and fallback oracles. The main oracle oracle is the most trustworthy price source, the pivot oracle is is
```suggestion
The way the Resilient Oracle works is for every market (vToken) we configure the main, pivot and fallback oracles. The main oracle oracle is the most trustworthy price source, the pivot oracle is is used as a loose sanity checker and the fallback oracle is used as a backup price source.
```

2022-11-24 13:21 UTC, 0xlucian commented on oracle/ResillientOracle.md
> +To validate the price between two oracles we set an upper and lower bound ratio for every market. The upper bound ratio represents the deviation between reported prices (price from oracle that’s bein
```suggestion
To validate the price between two oracles we set an **upper** and **lower** bound ratio for every market. The **upper bound ratio** represents the **deviation** between **reported prices** (price from oracle that’s being validated) and anchor price (price from oracle we are validating against) beyond which the reported price will be invalidated. And the **lower bound ratio** presents the **deviation** between **reported price and anchor price** below which the reported price will be invalidated. So for oracle price to be considered valid the below statement should be true:
```

2022-11-25 12:57 UTC, web3rover commented on oracle/ResillientOracle.md
> +Keeping this in mind, we have designed a resilient oracle which uses multiple oracle sources to validate prices and fallback mechanisms to provide accurate prices and protect from oracle attacks. Cur
Updated

2022-11-28 13:06 UTC, 0xlucian approved these changes

2022-11-29 14:11 UTC, merged