[VEN789] [VEN-747] docs: Edit oracle doc descriptions
VenusProtocol/venus-protocol-documentation pull request #29
Opened 2023-01-16 17:16 UTC by coreyar

Edits Oracle doc introduction and details for clarity.

Adds most recent nat spec

2023-05-11 10:22 UTC, 0xlucian requested changes

2023-05-11 10:22 UTC, 0xlucian commented on oracles/binance.md
> +This oracle fetchs prices of assets from the Binance oracle.
```suggestion
This oracle fetches prices of assets from the Binance oracle.
```

2023-05-11 10:22 UTC, 0xlucian commented on oracles/chainlink.md
> +This oracle fetchs prices of assets from the Chainlink oracle.
```suggestion
This oracle fetches prices of assets from the Chainlink oracle.
```

2023-05-11 10:22 UTC, 0xlucian commented on oracles/pyth.md
> +This oracle fetches price of assets from the Pyth oracle
```suggestion
This oracle fetches price of assets from the Pyth oracle.
```

2023-06-14 10:06 UTC, chechu commented
Included in https://github.com/VenusProtocol/venus-protocol-documentation/pull/35

2023-06-14 10:06 UTC, closed without merging